name: Corremos Test

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: cancel running workflows
        uses: everphone-gmbh/cancel-previous-workflows@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Instalar Dependencias
        run: npm ci
      - name: Correr NPM Test
        run: npm test
  
  build:
    needs: [test]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Instalar Dependencias
        run: npm ci
      - name: Correr NPM Build
        run: npm run build