name: Corremos Test

on:
  push:
    branches: ["master"]

jobs:
  hola_mundo:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Instalar Dependencias
        run: npm ci
      - name: Correr NPM
        run: npm test