name: Corremos Test

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancelar Workflows Previos
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Instalar Dependencias
        run: npm ci
      - name: Correr NPM Test
        run: npm test
  
  build:
    needs: [test]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Instalar Dependencias
        run: npm ci
      - name: Correr NPM Build
        run: npm run build